apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - kustomizeconfig/servicemonitor.yaml



commonLabels:
  app.kubernetes.io/component: controller-manager

bases:
- ../../base

resources:
- service-monitor.yaml
- service.yaml

patchesStrategicMerge:
- manager.yaml


vars:
  - name: METRIC_SERVICE_NAME
    objref:
      kind: Service
      name: controller-manager-metrics
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name