apiVersion: v1
kind: Service
metadata:
  name: controller-manager-metrics
  namespace: system
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  clusterIP: None
  ports:
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: metrics