apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      imagePullSecrets:
        - name: codefresh-generated-r.cfcr.io-cfcr-ddev-live